/** English (default) strings for AtriumUI Home Dashboard. */
export const en = {
  'home.title': 'Home',
  'home.greeting.morning': 'Good morning',
  'home.greeting.noon': 'Good afternoon',
  'home.greeting.evening': 'Good evening',
  'home.greeting.night': 'Good night',
  'home.back': 'Back',
  'home.no_rooms': 'No rooms configured',
  'home.no_entities': 'No entities in this room',
  'home.presence': 'People',
  'home.presence.home': 'Home',
  'home.presence.away': 'Away',
  'home.bulk.all_off': 'All off',
  'home.show_more': 'Show more',
  'home.show_less': 'Show less',
  'home.quick_actions': 'Quick actions',
  'home.entity_missing': 'Entity not found',
  'home.confirm': 'Confirm',
  'home.cancel': 'Cancel',
  'device.unsupported_domain': 'Unsupported domain',
  'device.open': 'Open',
  'device.close': 'Close',
  'device.stop': 'Stop',
  'device.start': 'Start',
  'device.pause': 'Pause',
  'device.return': 'Return home',
  'device.timer_start': 'Start timer',
  'device.timer_cancel': 'Cancel timer',
  'device.timer_min': 'min',
  'fan.speed': 'Speed',
  'fan.oscillate': 'Oscillate',
  'fan.direction': 'Direction',
  'fan.direction.forward': 'Forward',
  'fan.direction.reverse': 'Reverse',
  'fan.preset': 'Preset',
  'fan.off': 'Off',
  'calendar.title': 'Calendar',
  'calendar.no_events': 'No events',
  'calendar.error': 'Could not load calendar',
  'calendar.all_day': 'All day',
  'calendar.fullscreen': 'Fullscreen',
  'calendar.close': 'Close',
  'calendar.refresh': 'Refresh',
  'calendar.filter': 'Filter',
  'calendar.prev_month': 'Previous month',
  'calendar.next_month': 'Next month',
  'calendar.view.agenda': 'Agenda',
  'calendar.view.today': 'Today',
  'calendar.view.week': 'Week',
  'calendar.view.month': 'Month',
  'calendar.location': 'Location',
  'calendar.description': 'Notes',
  'calendar.more_events': '+{n} more',
} as const;

export type TranslationKey = keyof typeof en;
