/** English (default) strings for AtriumUI Home Dashboard. */
export const en = {
  'home.title': 'Home',
  'home.greeting.morning': 'Good morning',
  'home.greeting.noon': 'Good afternoon',
  'home.greeting.evening': 'Good evening',
  'home.greeting.night': 'Good night',
  'home.back': 'Back',
  'home.no_rooms': 'No rooms configured',
  'home.no_entities': 'No entities in this room',
  'home.presence': 'People',
  'home.presence.home': 'Home',
  'home.presence.away': 'Away',
  'home.bulk.all_off': 'All off',
  'home.show_more': 'Show more',
  'home.show_less': 'Show less',
  'home.quick_actions': 'Quick actions',
  'home.entity_missing': 'Entity not found',
  'home.confirm': 'Confirm',
  'home.cancel': 'Cancel',
  'device.unsupported_domain': 'Unsupported domain',
  'device.open': 'Open',
  'device.close': 'Close',
  'device.stop': 'Stop',
  'device.start': 'Start',
  'device.pause': 'Pause',
  'device.return': 'Return home',
  'device.timer_start': 'Start timer',
  'device.timer_cancel': 'Cancel timer',
  'device.timer_min': 'min',
  'fan.speed': 'Speed',
  'fan.oscillate': 'Oscillate',
  'fan.direction': 'Direction',
  'fan.direction.forward': 'Forward',
  'fan.direction.reverse': 'Reverse',
  'fan.preset': 'Preset',
  'fan.off': 'Off',
  'calendar.title': 'Calendar',
  'calendar.no_events': 'No events',
  'calendar.error': 'Could not load calendar',
  'calendar.all_day': 'All day',
  'calendar.fullscreen': 'Fullscreen',
  'calendar.close': 'Close',
  'calendar.refresh': 'Refresh',
  'calendar.filter': 'Filter',
  'calendar.prev_month': 'Previous month',
  'calendar.next_month': 'Next month',
  'calendar.view.agenda': 'Agenda',
  'calendar.view.today': 'Today',
  'calendar.view.week': 'Week',
  'calendar.view.month': 'Month',
  'calendar.location': 'Location',
  'calendar.description': 'Notes',
  'calendar.more_events': '+{n} more',
  'drawer.open': 'Open settings',
  'drawer.close': 'Close settings',
  'drawer.theme': 'Theme',
  'drawer.theme.light': 'Light',
  'drawer.theme.dark': 'Dark',
  'drawer.theme.system': 'System',
  'drawer.edit': 'Enter edit mode',
  'drawer.dashboard': 'Dashboard settings',
  'drawer.global': 'Global configuration',
  'drawer.automations': 'Automations',
  'drawer.settings.show_presence': 'Show presence strip',
  'drawer.settings.show_bulk_actions': 'Show room “All off”',
  'drawer.settings.header_greeting': 'Time-of-day greeting as Home title',
  'drawer.settings.header_title': 'Home title (when greeting is off)',
  'drawer.settings.clock_format': 'Clock time format',
  'drawer.settings.clock_24h': '24-hour',
  'drawer.settings.clock_12h': '12-hour',
  'drawer.settings.clock_show_date': 'Show date on clock',
  'drawer.settings.clock_date_format': 'Date format',
  'drawer.settings.clock_show_day': 'Show weekday on clock',
  'drawer.settings.clock_day_format': 'Weekday format',
  'drawer.settings.clock_day_short': 'Short',
  'drawer.settings.clock_day_long': 'Long',
  'drawer.settings.room_idle_timeout': 'Return to Home after idle (seconds, 0 = off)',
  'drawer.settings.columns': 'Grid columns',
  'drawer.settings.gap': 'Grid gap',
  'drawer.settings.row_height': 'Row height',
  'drawer.settings.rows': 'Equal-height row tracks',
  'drawer.settings.max_rows': 'Maximum rows',
  'drawer.settings.width': 'Dashboard width',
  'drawer.settings.height': 'Dashboard height',
  'drawer.settings.auto_areas': 'Auto-discover entities from room area',
  'drawer.settings.confirm_actions': 'Confirm high-stakes actions',
  'drawer.settings.prefer_device_name': 'Prefer device registry names',
  'drawer.settings.room_controls_show': 'Show room light/switch strip by default',
  'drawer.automations.empty': 'No automations found',
  'drawer.automations.unavailable': 'Unavailable',
  'drawer.automations.run': 'Run',
  'drawer.automations.enable': 'Enable',
  'drawer.automations.disable': 'Disable',
} as const;

export type TranslationKey = keyof typeof en;
