import type { TranslationKey } from './en';

/** Hebrew strings for AtriumUI Home Dashboard (RTL). */
export const he: Record<TranslationKey, string> = {
  'home.title': 'בית',
  'home.greeting.morning': 'בוקר טוב',
  'home.greeting.noon': 'צהריים טובים',
  'home.greeting.evening': 'ערב טוב',
  'home.greeting.night': 'לילה טוב',
  'home.back': 'חזרה',
  'home.no_rooms': 'לא הוגדרו חדרים',
  'home.no_entities': 'אין ישויות בחדר זה',
  'home.presence': 'אנשים',
  'home.presence.home': 'בבית',
  'home.presence.away': 'לא בבית',
  'home.bulk.all_off': 'כבה הכל',
  'home.show_more': 'הצג עוד',
  'home.show_less': 'הצג פחות',
  'home.quick_actions': 'פעולות מהירות',
  'home.entity_missing': 'הישות לא נמצאה',
  'home.confirm': 'אישור',
  'home.cancel': 'ביטול',
  'device.unsupported_domain': 'תחום לא נתמך',
  'device.open': 'פתח',
  'device.close': 'סגור',
  'device.stop': 'עצור',
  'device.start': 'התחל',
  'device.pause': 'השהה',
  'device.return': 'חזרה לבסיס',
  'device.timer_start': 'הפעל טיימר',
  'device.timer_cancel': 'בטל טיימר',
  'device.timer_min': 'דק׳',
  'fan.speed': 'מהירות',
  'fan.oscillate': 'נדנוד',
  'fan.direction': 'כיוון',
  'fan.direction.forward': 'קדימה',
  'fan.direction.reverse': 'אחורה',
  'fan.preset': 'מצב',
  'fan.off': 'כבוי',
  'calendar.title': 'לוח שנה',
  'calendar.no_events': 'אין אירועים',
  'calendar.error': 'לא ניתן לטעון את לוח השנה',
  'calendar.all_day': 'כל היום',
  'calendar.fullscreen': 'מסך מלא',
  'calendar.close': 'סגור',
  'calendar.refresh': 'רענון',
  'calendar.filter': 'סינון',
  'calendar.prev_month': 'חודש קודם',
  'calendar.next_month': 'חודש הבא',
  'calendar.view.agenda': 'סדר יום',
  'calendar.view.today': 'היום',
  'calendar.view.week': 'שבוע',
  'calendar.view.month': 'חודש',
  'calendar.location': 'מיקום',
  'calendar.description': 'הערות',
  'calendar.more_events': '+עוד {n}',
  'drawer.open': 'פתח הגדרות',
  'drawer.close': 'סגור הגדרות',
  'drawer.theme': 'ערכת נושא',
  'drawer.theme.light': 'בהיר',
  'drawer.theme.dark': 'כהה',
  'drawer.theme.system': 'מערכת',
  'drawer.edit': 'מצב עריכה',
  'drawer.dashboard': 'הגדרות לוח בקרה',
  'drawer.global': 'הגדרות כלליות',
  'drawer.automations': 'אוטומציות',
  'drawer.settings.show_presence': 'הצג פס נוכחות',
  'drawer.settings.show_bulk_actions': 'הצג «כבה הכל» בחדר',
  'drawer.settings.header_greeting': 'ברכת שעה ככותרת הבית',
  'drawer.settings.header_title': 'כותרת הבית (כשאין ברכה)',
  'drawer.settings.clock_format': 'פורמט שעון',
  'drawer.settings.clock_24h': '24 שעות',
  'drawer.settings.clock_12h': '12 שעות',
  'drawer.settings.clock_show_date': 'הצג תאריך בשעון',
  'drawer.settings.clock_date_format': 'פורמט תאריך',
  'drawer.settings.clock_show_day': 'הצג יום בשבוע בשעון',
  'drawer.settings.clock_day_format': 'פורמט יום בשבוע',
  'drawer.settings.clock_day_short': 'קצר',
  'drawer.settings.clock_day_long': 'ארוך',
  'drawer.settings.room_idle_timeout': 'חזרה לבית אחרי חוסר פעילות (שניות, 0 = כבוי)',
  'drawer.settings.columns': 'עמודות רשת',
  'drawer.settings.gap': 'רווח רשת',
  'drawer.settings.row_height': 'גובה שורה',
  'drawer.settings.rows': 'שורות בגובה שווה',
  'drawer.settings.max_rows': 'מקסימום שורות',
  'drawer.settings.width': 'רוחב לוח הבקרה',
  'drawer.settings.height': 'גובה לוח הבקרה',
  'drawer.settings.auto_areas': 'גלה ישויות מאזור החדר',
  'drawer.settings.confirm_actions': 'אשר פעולות חשובות',
  'drawer.settings.prefer_device_name': 'העדף שמות מכשירים',
  'drawer.settings.room_controls_show': 'הצג פס תאורה/מתגים בחדר כברירת מחדל',
};
