import type { TranslationKey } from './en';

/** Hebrew strings for AtriumUI Home Dashboard (RTL). */
export const he: Record<TranslationKey, string> = {
  'home.title': 'בית',
  'home.greeting.morning': 'בוקר טוב',
  'home.greeting.noon': 'צהריים טובים',
  'home.greeting.evening': 'ערב טוב',
  'home.greeting.night': 'לילה טוב',
  'home.back': 'חזרה',
  'home.no_rooms': 'לא הוגדרו חדרים',
  'home.no_entities': 'אין ישויות בחדר זה',
  'home.presence': 'אנשים',
  'home.presence.home': 'בבית',
  'home.presence.away': 'לא בבית',
  'home.bulk.all_off': 'כבה הכל',
  'home.show_more': 'הצג עוד',
  'home.show_less': 'הצג פחות',
  'home.quick_actions': 'פעולות מהירות',
  'home.entity_missing': 'הישות לא נמצאה',
  'home.confirm': 'אישור',
  'home.cancel': 'ביטול',
  'device.unsupported_domain': 'תחום לא נתמך',
  'device.open': 'פתח',
  'device.close': 'סגור',
  'device.stop': 'עצור',
  'device.start': 'התחל',
  'device.pause': 'השהה',
  'device.return': 'חזרה לבסיס',
  'device.timer_start': 'הפעל טיימר',
  'device.timer_cancel': 'בטל טיימר',
  'device.timer_min': 'דק׳',
  'fan.speed': 'מהירות',
  'fan.oscillate': 'נדנוד',
  'fan.direction': 'כיוון',
  'fan.direction.forward': 'קדימה',
  'fan.direction.reverse': 'אחורה',
  'fan.preset': 'מצב',
  'fan.off': 'כבוי',
  'calendar.title': 'לוח שנה',
  'calendar.no_events': 'אין אירועים',
  'calendar.error': 'לא ניתן לטעון את לוח השנה',
  'calendar.all_day': 'כל היום',
  'calendar.expand': 'הרחב',
  'calendar.collapse': 'כווץ',
  'calendar.close': 'סגור',
  'calendar.view.agenda': 'סדר יום',
  'calendar.view.today': 'היום',
  'calendar.view.week': 'שבוע',
  'calendar.view.month': 'חודש',
  'calendar.location': 'מיקום',
  'calendar.description': 'הערות',
};
