import type { TranslationKey } from './en';

/** Russian strings for AtriumUI Home Dashboard. */
export const ru: Record<TranslationKey, string> = {
  'home.title': 'Дом',
  'home.greeting.morning': 'Доброе утро',
  'home.greeting.noon': 'Добрый день',
  'home.greeting.evening': 'Добрый вечер',
  'home.greeting.night': 'Доброй ночи',
  'home.back': 'Назад',
  'home.no_rooms': 'Комнаты не настроены',
  'home.no_entities': 'В этой комнате нет устройств',
  'home.presence': 'Люди',
  'home.presence.home': 'Дома',
  'home.presence.away': 'Вне дома',
  'home.bulk.all_off': 'Выключить всё',
  'home.show_more': 'Показать ещё',
  'home.show_less': 'Свернуть',
  'home.quick_actions': 'Быстрые действия',
  'home.entity_missing': 'Сущность не найдена',
  'home.confirm': 'Подтвердить',
  'home.cancel': 'Отмена',
  'device.unsupported_domain': 'Неподдерживаемый домен',
  'device.open': 'Открыть',
  'device.close': 'Закрыть',
  'device.stop': 'Стоп',
  'device.start': 'Старт',
  'device.pause': 'Пауза',
  'device.return': 'На базу',
  'device.timer_start': 'Таймер',
  'device.timer_cancel': 'Отменить таймер',
  'device.timer_min': 'мин',
  'fan.speed': 'Скорость',
  'fan.oscillate': 'Поворот',
  'fan.direction': 'Направление',
  'fan.direction.forward': 'Вперёд',
  'fan.direction.reverse': 'Назад',
  'fan.preset': 'Режим',
  'fan.off': 'Выкл',
  'calendar.title': 'Календарь',
  'calendar.no_events': 'Нет событий',
  'calendar.error': 'Не удалось загрузить календарь',
  'calendar.all_day': 'Весь день',
  'calendar.fullscreen': 'На весь экран',
  'calendar.close': 'Закрыть',
  'calendar.refresh': 'Обновить',
  'calendar.filter': 'Фильтр',
  'calendar.prev_month': 'Предыдущий месяц',
  'calendar.next_month': 'Следующий месяц',
  'calendar.view.agenda': 'Расписание',
  'calendar.view.today': 'Сегодня',
  'calendar.view.week': 'Неделя',
  'calendar.view.month': 'Месяц',
  'calendar.location': 'Место',
  'calendar.description': 'Заметки',
  'calendar.more_events': '+ещё {n}',
  'drawer.open': 'Открыть настройки',
  'drawer.close': 'Закрыть настройки',
  'drawer.theme': 'Тема',
  'drawer.theme.light': 'Светлая',
  'drawer.theme.dark': 'Тёмная',
  'drawer.theme.system': 'Системная',
  'drawer.edit': 'Режим правки',
  'drawer.dashboard': 'Настройки панели',
  'drawer.global': 'Общие настройки',
  'drawer.automations': 'Автоматизации',
  'drawer.settings.show_presence': 'Показывать присутствие',
  'drawer.settings.show_bulk_actions': 'Показывать «Выключить всё»',
  'drawer.settings.header_greeting': 'Приветствие по времени суток',
  'drawer.settings.header_title': 'Заголовок Home (без приветствия)',
  'drawer.settings.clock_format': 'Формат часов',
  'drawer.settings.clock_24h': '24 часа',
  'drawer.settings.clock_12h': '12 часов',
  'drawer.settings.clock_show_date': 'Показывать дату на часах',
  'drawer.settings.clock_date_format': 'Формат даты',
  'drawer.settings.clock_show_day': 'Показывать день недели',
  'drawer.settings.clock_day_format': 'Формат дня недели',
  'drawer.settings.clock_day_short': 'Короткий',
  'drawer.settings.clock_day_long': 'Полный',
  'drawer.settings.room_idle_timeout': 'Возврат на Home после простоя (сек, 0 = выкл.)',
  'drawer.settings.columns': 'Колонки сетки',
  'drawer.settings.gap': 'Зазор сетки',
  'drawer.settings.row_height': 'Высота строки',
  'drawer.settings.rows': 'Равные строки по высоте',
  'drawer.settings.max_rows': 'Максимум строк',
  'drawer.settings.width': 'Ширина панели',
  'drawer.settings.height': 'Высота панели',
  'drawer.settings.auto_areas': 'Подставлять сущности из области комнаты',
  'drawer.settings.confirm_actions': 'Подтверждать важные действия',
  'drawer.settings.prefer_device_name': 'Предпочитать имена устройств',
  'drawer.settings.room_controls_show': 'Показывать полосу света/выключателей по умолчанию',
  'drawer.automations.empty': 'Автоматизации не найдены',
  'drawer.automations.unavailable': 'Недоступна',
  'drawer.automations.run': 'Запустить',
  'drawer.automations.enable': 'Включить',
  'drawer.automations.disable': 'Выключить',
};
