import type { TranslationKey } from './en';

/** Russian strings for AtriumUI Home Dashboard. */
export const ru: Record<TranslationKey, string> = {
  'home.title': 'Дом',
  'home.greeting.morning': 'Доброе утро',
  'home.greeting.noon': 'Добрый день',
  'home.greeting.evening': 'Добрый вечер',
  'home.greeting.night': 'Доброй ночи',
  'home.back': 'Назад',
  'home.no_rooms': 'Комнаты не настроены',
  'home.no_entities': 'В этой комнате нет устройств',
  'home.presence': 'Люди',
  'home.presence.home': 'Дома',
  'home.presence.away': 'Вне дома',
  'home.bulk.all_off': 'Выключить всё',
  'home.show_more': 'Показать ещё',
  'home.show_less': 'Свернуть',
  'home.quick_actions': 'Быстрые действия',
  'home.entity_missing': 'Сущность не найдена',
  'home.confirm': 'Подтвердить',
  'home.cancel': 'Отмена',
  'device.unsupported_domain': 'Неподдерживаемый домен',
  'device.open': 'Открыть',
  'device.close': 'Закрыть',
  'device.stop': 'Стоп',
  'device.start': 'Старт',
  'device.pause': 'Пауза',
  'device.return': 'На базу',
  'device.timer_start': 'Таймер',
  'device.timer_cancel': 'Отменить таймер',
  'device.timer_min': 'мин',
  'fan.speed': 'Скорость',
  'fan.oscillate': 'Поворот',
  'fan.direction': 'Направление',
  'fan.direction.forward': 'Вперёд',
  'fan.direction.reverse': 'Назад',
  'fan.preset': 'Режим',
  'fan.off': 'Выкл',
  'calendar.title': 'Календарь',
  'calendar.no_events': 'Нет событий',
  'calendar.error': 'Не удалось загрузить календарь',
  'calendar.all_day': 'Весь день',
  'calendar.expand': 'Развернуть',
  'calendar.collapse': 'Свернуть',
  'calendar.close': 'Закрыть',
  'calendar.view.agenda': 'Расписание',
  'calendar.view.today': 'Сегодня',
  'calendar.view.week': 'Неделя',
  'calendar.view.month': 'Месяц',
  'calendar.location': 'Место',
  'calendar.description': 'Заметки',
};
